2016-01-08 08:42:08,605 [Thread-8124:26976] [logger:41] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\page\timing_manage.py", line 38, in timing_manage_list
    logger.debug("current job status: {0}".format(scheduler.print_jobs()))
  File "C:\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 555, in print_jobs
    jobs = store.get_all_jobs()
  File "C:\Python27\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 73, in get_all_jobs
    jobs = self._get_jobs()
  File "C:\Python27\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 124, in _get_jobs
    for row in self.engine.execute(selectable):
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\lib\site-packages\MySQLdb\cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT apscheduler_jobs.id, apscheduler_jobs.job_state \nFROM apscheduler_jobs ORDER BY apscheduler_jobs.next_run_time']

2016-01-08 08:43:10,888 [Thread-8161:26728] [logger:38] [DEBUG]- current job status: None
2016-01-08 08:49:20,717 [Thread-8270:23016] [logger:38] [DEBUG]- current job status: None
2016-01-08 08:51:24,657 [Thread-8325:21896] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 08:52:06,907 [Thread-8382:1124] [logger:38] [DEBUG]- current job status: None
2016-01-08 09:28:42,907 [Thread-9497:26340] [logger:38] [DEBUG]- current job status: None
2016-01-08 09:30:31,993 [Thread-9571:27192] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 09:43:25,502 [Thread-10116:27388] [logger:38] [DEBUG]- current job status: None
2016-01-08 09:50:15,421 [Thread-10319:26784] [logger:38] [DEBUG]- current job status: None
2016-01-08 09:51:06,276 [Thread-10419:22348] [logger:38] [DEBUG]- current job status: None
2016-01-08 09:58:14,963 [Thread-10488:18416] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:03:25,836 [Thread-10719:27556] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:04:08,911 [Thread-10784:19216] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:06:12,118 [Thread-10875:23284] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:06:30,392 [Thread-10934:25160] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:09:14,311 [Thread-10978:26800] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:10:17,552 [Thread-11078:27284] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:16:50,831 [Thread-11374:23248] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:19:09,344 [Thread-11437:26904] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:24:09,500 [Thread-11540:25628] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 10:27:21,744 [Thread-11646:26720] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:30:05,536 [Thread-11729:21588] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:31:09,921 [Thread-11883:21060] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:34:26,380 [Thread-12179:26892] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:41:36,174 [Thread-12742:27424] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 10:43:18,342 [Thread-12911:26668] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:18,733 [Thread-12913:5696] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:20,042 [Thread-12921:26248] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:21,105 [Thread-12931:25304] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:21,332 [Thread-12933:27360] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:21,615 [Thread-12935:26500] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:43:21,834 [Thread-12937:10420] [logger_files:584] [ERROR]- Traceback (most recent call last):
  File "D:\work\Aptana Studio 3 Workspace\ujobs\source\ujobs\apps\files\views.py", line 574, in ajax_show_exec_type_detail
    time_taken = (datetime.datetime.now()-history_step.start_time.replace(tzinfo=None)).seconds
AttributeError: 'NoneType' object has no attribute 'replace'

2016-01-08 10:44:30,653 [Thread-13046:24324] [logger:38] [DEBUG]- current job status: None
2016-01-08 10:52:29,571 [Thread-13746:27152] [logger:38] [DEBUG]- current job status: None
2016-01-08 11:24:44,109 [Thread-17088:4652] [logger:38] [DEBUG]- current job status: None
2016-01-08 11:38:08,575 [Thread-18181:5264] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 11:38:46,354 [Thread-18337:26132] [logger:38] [DEBUG]- current job status: None
2016-01-08 13:34:29,793 [Thread-27642:22432] [logger:40] [DEBUG]- [user login] luozh login ok.
2016-01-08 14:08:03,832 [Thread-29747:23036] [logger:38] [DEBUG]- current job status: None
